nbi:
  httpVersion: 1
  useTLS: no
  fqdn: 3gpp-monitoing-event.local
  port: 8080

sbi:
  identitySvc: http://ue-identity-service:8080
  redisSvc: redis:6379
  httpVersion: 2

supportedFeatures: 3fff # 12 for open5gs, 3fff for free5gs
capifSvc: capif-connector:8080
