nbi:
  httpVersion: 1
  useTLS: no
  fqdn: 3gpp-traffic-influence.local
  port: 8080

sbi:
  nrfSvc: http://nrf.net01.3gpp.eurecom.fr
  useNrf: no
  pcfSvc: http://core-simulator:8080
  httpVersion: 2

supportedFeatures: 3fff # 12 for open5gs, 3fff for free5gs, 3fff for oai
capifSvc: capif-connector:8080
